name: auth

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  redis:
    image: redis:latest
    environment:
        REDIS_PASSWORD: 1234
        REDIS_USER: user
        REDIS_USER_PASSWORD: 1234
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data